### ISSUE TITLE
学生ページの課題一覧

### ISSUE THREAD

**Issue by maya40421** [ProceduralProgrammingTA/TOJWebapp#15]
* 提出が AC なのに、学生の課題一覧のページを見ると WA になっている
  * 3, 4件ほど報告されていた
    * 内ほとんどに関しては、もう一度 AC のコードを提出すると課題一覧のページの方も更新されていた
      * 内1研に関して、admin からその生徒の課題状況を見るとちゃんと AC となっていた
    * 1件だけ、もう一度投げて AC しても課題一覧のページの方が WA のままだった事例が存在した
      * そのケースに関して、課題一覧の ex2 の最終提出時刻が、 ex1 のとある提出の時刻になっていて更新されていない、という現象が確認できた
        * 他のもう一度提出すると直った事例において同様の現象が起きているかは未検証
  * テストアカウントにより再現を試みたが失敗
  * ここの SQL が怪しそう？ https://github.com/ProceduralProgrammingTA/TOJWebapp/blob/master/app/controllers/home_controller.rb

**Comment by riantkb** [comment]
@maya40421 
学生トップページの課題一覧からは WA に見えてるけど提出履歴で見るとちゃんと AC になっている問題、調査してみたら、その現象が発生した提出のひとつで、その現象が起きている提出のひとつ前の提出が WA で、かつ **秒単位で同時刻に提出されていた** のを確認できました。
偶然とも思えないので、少なくとも原因のひとつに、秒単位で同時刻の提出がある場合にその中で一番若いものの status を取ってきてしまう、というのが考えられるかもしれないです。

**Comment by riantkb** [comment]
えー、完全に理解をして、https://github.com/ProceduralProgrammingTA/TOJWebapp/blob/master/app/controllers/home_controller.rb で最新の提出を取ってくるために `submission_time` にその学生の各問題に対する提出時刻の max を取っていましたが、その後で **全提出に対して** created_at がその集合に含まれているかの判定をしているので、同時刻に提出された他の学生の提出も持ってきてしまい、その後の join で他の学生の提出が入ってきてしまう、という状況になっていそうです

**Comment by riantkb** [comment]
これを解決する方法として、
- 全提出に対してではなくその学生の提出のみに対して判定をする（同じ学生が1秒間に複数の提出をしてきた場合崩壊しますが…）
- そもそも id など順番が定義されていてかつ一意に定まる物を利用する
などがある気がします。

意見を伺いたいです。

**Comment by riantkb** [comment]
おそらく解決したはず（一応次回の授業で起きないか呼びかけてみます）
