### ISSUE TITLE
ファイルを選択せずに提出ボタンを押すとサーバーエラー画面(レポート)

### ISSUE THREAD

**Issue by m1kit** [ProceduralProgrammingTA/TOJWebapp#51]
レポート提出画面でも https://github.com/ProceduralProgrammingTA/TOJWebapp/issues/32 と同じ現象が起こるようです。
本来ならばPRを送って気の利いた学生をしたかったんですが、期末試験と課題が忙しいのでゆるしてほしい

**Comment by riantkb** [comment]
done
